# Generated by Django 6.0.6 on 2026-06-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='completado',
        ),
        migrations.AddField(
            model_name='actividad',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROGRESO', 'En progreso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20),
        ),
    ]
