# Generated by Django 6.0.4 on 2026-07-03 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_delete_diatracking_remove_registrodia_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='vio_scratch',
        ),
    ]
