# Generated by Django 6.0.4 on 2026-07-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_profile_vio_scratch'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vio_scratch',
            field=models.BooleanField(default=False),
        ),
    ]
