# Generated by Django 6.0.4 on 2026-07-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_vio_scratch'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_scratch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
